//q2
'use strict'
let stepCounter={
    step:0,
    increase:function(){
        this.step++;  
    },
    decrease:function()
    {
        this.step--;
    },
    reset:function()
    {
        this.step=0;
    },
    read:function()
    {
        console.log(this.step);
    },
};
stepCounter.increase();
stepCounter.increase();
stepCounter.increase();
stepCounter.increase();
stepCounter.decrease();
stepCounter.decrease();
stepCounter.read()
stepCounter.reset();
stepCounter.read()